script
unstoppabledomains/dot-crypto pull request #53
Opened 2021-06-08 04:45 UTC by JohnnyJumper

Not sure if there is any way to speed the script up. The bottleneck is the CoinGecko API rate limit. I found several mentions that the API can handle 100 requests/minute and one mention that API can handle 10 requests/second. In practice, the best I could do Is to have 2 requests / 1.5 seconds. It takes about 2.5hrs to get all the required information for each coin.

2021-06-08 17:53 UTC, DancingAxolotl commented on src/supported-keys/update.ts
> +    }
If all we need from coin details is the rating, then maybe it will be easier to request the whole list of top 200 coins using the `coins/markets` endpoint with the `order` parameter set to `gecko_desc` - https://www.coingecko.com/api/documentations/v3#/coins/get_coins_markets

It returns a bunch of extra data, but most importantly it provides a list of coin IDs and coin names in the order that we need. Unfortunately, it does not provide platform data. So we still have to request `coins/list/include_platform=true` and combine the two lists.

This should allow us to retrieve all the necessary data in just two requests.

2021-06-09 16:00 UTC, DeRain commented on src/supported-keys/update.ts
> +    }
@DancingAxolotl  Good idea!

2021-06-09 16:06 UTC, DeRain requested changes

2021-06-09 16:06 UTC, DeRain commented on src/supported-keys/update.ts
> +const getCoinDetails = async (coinId: string): Promise<CoinGeckoCoinDetailResponse> => {
Please try query a whole list of coins with details as it mentioned above and don't use 1 HTTP request for each coin

2021-06-09 16:06 UTC, DeRain commented on src/supported-keys/update.ts
> +      case 'ethereum-classic':
You may need to detect Binance chain and Binance Smart chain (they are different).
The coins comes from these platforms have their own standard tickers (like ERC20). 

Please mark these coins as BEP2 or BEP20 if it's correct format for them.

- https://academy.binance.com/en/glossary/bep-2
- https://academy.binance.com/en/glossary/bep-20

2021-06-09 18:14 UTC, JohnnyJumper commented on src/supported-keys/update.ts
> +      case 'ethereum-classic':
Got it! I never heard about bep2 or bep20 tickets before, I will the script and rerun it to get the new version of the results instead of [#54]

2021-06-10 09:13 UTC, DeRain approved these changes
👍 Nice job!

2021-06-11 02:22 UTC, merged