script result
unstoppabledomains/dot-crypto pull request #54
Opened 2021-06-08 04:46 UTC by JohnnyJumper

This is the result of running the update script from [ #53 ].

2021-06-08 05:57 UTC, JohnnyJumper commented on src/supported-keys/supported-keys.json
> +  "version": "1.1.1",
Is this needed to be updated? or this is just a mirror for the version from package.json?

2021-06-08 05:57 UTC, JohnnyJumper commented on src/supported-keys/supported-keys.json
> +      "deprecatedKeyName":  null,
As we are trying to move away from deprecatedKeyName I think it is ok to let it be null

2021-06-08 05:57 UTC, JohnnyJumper commented on src/supported-keys/supported-keys.json
> +    "crypto.LINK.version.HARMONYSHARD0.address": {
Some of the chains names ended up quite long. like this one HARMONYSHARD0. What can be a better name for it?

2021-06-09 16:07 UTC, DeRain commented on src/supported-keys/supported-keys.json
> +    "crypto.LINK.version.HARMONYSHARD0.address": {
@JohnnyJumper if you not sure - remove this coins till the better times

2021-06-09 16:10 UTC, DeRain requested changes

2021-06-09 16:10 UTC, DeRain commented on src/supported-keys/supported-keys.json
> +      "deprecatedKeyName":  null,
@JohnnyJumper It's not, website frontend still relies on that

2021-06-09 16:10 UTC, DeRain commented on src/supported-keys/supported-keys.json
> +    "crypto.ETH.version.BSC.address": {
BSC means Binance Smart Chain. I assume this is the BEP20 token, but you need to check

2021-06-09 16:10 UTC, DeRain commented on src/supported-keys/supported-keys.json
> +    "crypto.TUSD.version.BINANCECOIN.address": {
@JohnnyJumper Probably this is Binance Chain which means that the token might be BEP2 version. Please check.

2021-06-10 09:19 UTC, DeRain reviewed
@JohnnyJumper  Looks great! How much unique tickers was added (not considering versions)? If lesser than 200 it makes sense include more. The goal is to get 200 unique tickers.

2021-06-10 09:19 UTC, DeRain commented on src/supported-keys/supported-keys.json
> +  "version": "1.1.1",
Yes

2021-06-11 02:23 UTC, merged